include:
  - project: "jean.laneurit/ros_gitlab_ci"
    file: ".gitlab-ci.yml"


variables:
  PKGS_TO_BUILD_TEST: "romea_mobile_base_bringup romea_mobile_base_description romea_mobile_base_controllers romea_mobile_base_hardware romea_mobile_base_utils"
